<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-08-16 22:50

from django.conf import settings
=======
# Generated by Django 3.2.14 on 2022-08-22 07:34

from django.conf import settings
import django.core.validators
>>>>>>> cce6dda622ac49ffca6c75bd728a20c71d57f42d
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_image', models.ImageField(null=True, upload_to='courses/images')),
<<<<<<< HEAD
                ('course_created_at', models.DateTimeField(auto_now_add=True)),
                ('course_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='category.category')),
                ('course_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_course', to=settings.AUTH_USER_MODEL)),
                ('student_course_name', models.ManyToManyField(null=True, related_name='student_course', to=settings.AUTH_USER_MODEL)),
=======
                ('course_rate', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('course_created_at', models.DateTimeField(auto_now_add=True)),
                ('course_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='category.category')),
                ('course_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_course', to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, null=True, related_name='enroll', to=settings.AUTH_USER_MODEL)),
>>>>>>> cce6dda622ac49ffca6c75bd728a20c71d57f42d
            ],
        ),
    ]
