# Generated by Django 3.2.13 on 2022-08-07 13:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_image', models.ImageField(null=True, upload_to='courses/images')),
                ('course_rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('course_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_course_name', models.ManyToManyField(related_name='student_course', to='course.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userCourse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
