# Generated by Django 3.2.14 on 2022-08-08 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_course_name',
            field=models.ManyToManyField(null=True, related_name='student_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student_Course',
        ),
    ]
