# Generated by Django 3.2.13 on 2022-08-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220807_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student_course_instructor',
            new_name='course_instructor',
        ),
    ]
