# Generated by Django 3.2.14 on 2022-08-02 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('course_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
