# Generated by Django 3.2.14 on 2022-08-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_course_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
    ]
