# Generated by Django 3.2.13 on 2022-06-22 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetPassword',
            new_name='ResetPasswordModel',
        ),
    ]
