<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-08-16 22:50
=======
# Generated by Django 3.2.14 on 2022-08-22 07:34
>>>>>>> cce6dda622ac49ffca6c75bd728a20c71d57f42d

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('url', models.FileField(upload_to='./media/video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
