# Generated by Django 3.2.13 on 2022-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('url', models.FileField(upload_to='./media/video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
