# Generated by Django 3.2.13 on 2022-08-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_video',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.video'),
            preserve_default=False,
        ),
    ]
